### ISSUE TITLE
Sass configuration missing from master config file?

### ISSUE THREAD

**Issue by jeromecovington** [madebysource/pho-devstack#61]
The configuration documentation points to this file: https://github.com/madebysource/pho-devstack/blob/master/config.js

It seems that this config file is meant to support all available options, but are Sass configuration options missing?

**Comment by PavelGavlik** [comment]
Well, Sass support is currently implemented as an extension. That means its configuration options aren't part of the main config file and you can find them in sass-support.js in your generated project folder. Available options are documented at https://github.com/dlmanning/gulp-sass and https://github.com/sass/node-sass#options

**Comment by jeromecovington** [comment]
Thanks, Pavel. I'll use the Sass support extension.
