### ISSUE TITLE
Any near future plans of replacing the deprecated libraries or extensions etc?

### ISSUE THREAD

**Issue by picwellwisher12pk** [madebysource/pho-devstack#63]
I found this. 
npm WARN deprecated gulp-clean@0.2.4: use gulp-rimraf instead
npm WARN deprecated ngmin@0.5.0: use ng-annotate instead
npm WARN optional dep failed, continuing gmsmith@0.4.5
npm WARN optional dep failed, continuing phantomjssmith@0.4.6
npm WARN optional dep failed, continuing fsevents@0.3.5

**Comment by PavelGavlik** [comment]
Yes, I'm going to replace deprecated packages. I've already replaced gulp-clean in master and browserify-ngmin will be replaced with gulp-ng-annotate. Other deps are probably just matter of upgrading gulp-imagemin.

**Comment by picwellwisher12pk** [comment]
Great. 
Can I ask for some more help? I am having some problems with Pho-devstack. I shall create a new thread if like.

**Comment by PavelGavlik** [comment]
Sure, create another issue
